development:
  driver:   "mongoose"
  host:     "localhost"
  database: "DREAMCOAT-dev"

test:
  driver:   "mongoose"
  host:     "localhost"
  database: "DREAMCOAT-test"

production:
  driver:   "mongoose"
  host:     "localhost"
  database: "DREAMCOAT-production"
